
DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER (ID INT PRIMARY KEY AUTO_INCREMENT, MEMBER_ID VARCHAR(255), PASSWORD VARCHAR(255), NAME VARCHAR(255));

INSERT INTO MEMBER (MEMBER_ID, PASSWORD, NAME) VALUES ('test', '{bcrypt}$2a$10$lxpqTR7ZKf8ruMQ8hGzuvuVXp9faOhvW4HvGemVdp6S7oyEmeiFx6', '테스트');
INSERT INTO MEMBER (MEMBER_ID, PASSWORD, NAME) VALUES ('admin', '{bcrypt}$2a$10$A835b1ZaSQSPteOgTSPHv.OtfdZwR9JWPVr3OrFGiSLlxr69QT65G', '관리자');


DROP TABLE IF EXISTS ROLES;

CREATE TABLE ROLES (ID INT PRIMARY KEY AUTO_INCREMENT, ROLE_CODE VARCHAR(255), ROLE_NAME VARCHAR(255));

INSERT INTO ROLES (ROLE_CODE, ROLE_NAME) VALUES ('ROLE_ADMIN', '관리자');
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME) VALUES ('ROLE_CUSTOMER', '일반회원');


DROP TABLE IF EXISTS MEMBER_ROLES;

CREATE TABLE MEMBER_ROLES (ID INT PRIMARY KEY AUTO_INCREMENT, MEMBER_ID VARCHAR(255), ROLE_CODE VARCHAR(255));

INSERT INTO MEMBER_ROLES (MEMBER_ID, ROLE_CODE) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO MEMBER_ROLES (MEMBER_ID, ROLE_CODE) VALUES ('admin', 'ROLE_CUSTOMER');
INSERT INTO MEMBER_ROLES (MEMBER_ID, ROLE_CODE) VALUES ('test', 'ROLE_CUSTOMER');


