--DROP TABLE IF EXISTS PRODUCT;
--
--CREATE TABLE PRODUCT (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), STATUS VARCHAR(255), PRICE INT(11));
--
--INSERT INTO PRODUCT (NAME, STATUS, PRICE) VALUES ('노트북', '01', 1200000);
--INSERT INTO PRODUCT (NAME, STATUS, PRICE) VALUES ('티셔츠', '01', 40000);
--INSERT INTO PRODUCT (NAME, STATUS, PRICE) VALUES ('TV', '02', 500000);
--INSERT INTO PRODUCT (NAME, STATUS, PRICE) VALUES ('볼펜', '01', 2000);

DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER (ID INT PRIMARY KEY AUTO_INCREMENT, MEMBER_ID VARCHAR(255), PASSWORD VARCHAR(255), NAME VARCHAR(255), ROLE VARCHAR(255));

INSERT INTO MEMBER (MEMBER_ID, PASSWORD, NAME, ROLE) VALUES ('test', '{bcrypt}$2a$10$lxpqTR7ZKf8ruMQ8hGzuvuVXp9faOhvW4HvGemVdp6S7oyEmeiFx6', '테스트', 'ROLE_CUSTOMER');
INSERT INTO MEMBER (MEMBER_ID, PASSWORD, NAME, ROLE) VALUES ('admin', '{bcrypt}$2a$10$A835b1ZaSQSPteOgTSPHv.OtfdZwR9JWPVr3OrFGiSLlxr69QT65G', '관리자', 'ROLE_ADMIN');