DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255), STATUS VARCHAR(255), PRICE INT(11));

INSERT INTO PRODUCT (NAME, STATUS, PRICE) VALUES ('노트북', '01', 1200000);
INSERT INTO PRODUCT (NAME, STATUS, PRICE) VALUES ('티셔츠', '01', 40000);
INSERT INTO PRODUCT (NAME, STATUS, PRICE) VALUES ('TV', '02', 500000);
INSERT INTO PRODUCT (NAME, STATUS, PRICE) VALUES ('볼펜', '01', 2000);
